language: node_js # 设置语言
node_js: stable # 设置相应版本
cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容
install:
  - npm install # 安装hexo及插件
script:
  - hexo clean # 清除
  - hexo g # 生成
  - hexo d
branches:
  only:
    - hexo # 只监测hexo分支