language: node_js
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
    
script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "samoz"
  - git config user.email "15176981781@163.com"
  - sed -i "s/Travis/${Travis}/g" ./_config.yml
  - hexo deploy